#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${zlt.datasource.ip}:3306/tng-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
#    username: ${zlt.datasource.username}
#    password: ${zlt.datasource.password}

sharding:
  jdbc:
    datasource:
      names: ds
      ds:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${zlt.datasource.ip}:3306/tng-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
        username: ${zlt.datasource.username}
        password: ${zlt.datasource.password}
    config:
      sharding:
        tables:
          tng_user:
            actual-data-nodes: ds.tng_user_${0..3}
            table-strategy:
              standard:
                sharding-column: username
                precise-algorithm-class-name: com.central.user.utils.MyPreciseShardingAlgorithmUtils
            #              inline:
            #                sharding-column: tngUserPhone
            #                algorithm-expression: tng_user_${tngUserPhone % 4}
            key-generator-column-name: id
      props:
        sql:
          show: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.tng.user.tnguser.model
  typeAliasesPackage: com.central.user.model
  global-config:
    db-config:
      id-type: id_worker

tng:
  snowflake:
    workerId: 1
    datacenterId: 1

debug: false